abstract final class AssetsManager {
  static const icAhadeth = "assets/images/ic_ahadeth.png";
  static const icRadio = "assets/images/ic_radio.png";
  static const icQuran = "assets/images/ic_quran.png";
  static const icSebha = "assets/images/ic_sebha.png";
  static const icPrayTimes = "assets/images/ic_pray_times.png";
  static const islamicNumbersBg = "assets/images/isalmic_numbers_bg.png";
  static const mainBackground = "assets/images/main_background.png";
  static const splashImage = "assets/images/splash_image.png";
  static const suraContentBg = "assets/images/sura_content_bg.png";
  static const ahadethBackground = "assets/images/ahadeth_background.png";
  static const islamiLogo = "assets/images/logo.png";
  static const recentSuraImage = "assets/images/recent_sura_image.png";
  static const titleLeftBg = "assets/images/title_bg_left.png";
  static const titleRightBg = "assets/images/title_bg_right.png";
  static const sebhaBackground = "assets/images/sebha_background.png";
  static const sebhaBody = "assets/images/sebha_body.png";
  static const sebhaMask = "assets/images/sebha_mask.png";
  static const welcome1 = "assets/images/welcome.png";
  static const welcome2 = "assets/images/welcome2.png";
  static const doaaimg = "assets/images/doaaimg.png";
  static const microphone = "assets/images/microphone.png";
  static const quranreading = "assets/images/quranreading.png";
}
